<?php
/**
 * Plugin Name:       Hide Block On Mobile
 * Description:       Adds a toggle in the block inspector to hide blocks on mobile via `hide-mobile` class.
 * Version: 2.0.1
 * Requires at least: 6.8
 * Requires PHP:      7.4
 * Author:            triopsi
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       hide-block-on-mobile
 *
 * @package CreateBlock
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Enqueue frontend CSS globally (so `hide-mobile` works even if the demo block is not used).
 * This file is generated by create-block from src/style.scss -> build/style-index.css
 */
function hbom_enqueue_frontend_styles() {
	$path = plugin_dir_path( __FILE__ ) . 'build/style-index.css';
	$url  = plugins_url( 'build/style-index.css', __FILE__ );

	if ( file_exists( $path ) ) {
		wp_enqueue_style(
			'hide-block-on-mobile-frontend',
			$url,
			array(),
			filemtime( $path )
		);
	}
}
add_action( 'wp_enqueue_scripts', 'hbom_enqueue_frontend_styles' );

/**
 * Enqueue editor CSS globally (visual marking only).
 * This file is generated by create-block from src/editor.scss -> build/index.css
 */
function hbom_enqueue_editor_styles() {
	$path = plugin_dir_path( __FILE__ ) . 'build/index.css';
	$url  = plugins_url( 'build/index.css', __FILE__ );

	if ( file_exists( $path ) ) {
		wp_enqueue_style(
			'hide-block-on-mobile-editor',
			$url,
			array(),
			filemtime( $path )
		);
	}
}
add_action( 'enqueue_block_editor_assets', 'hbom_enqueue_editor_styles' );

/**
 * Enqueue the add-on script globally in the block editor.
 * This ensures the filters (toggle + class) run for core blocks like core/image.
 */
function hbom_enqueue_editor_script() {
	$asset_path = plugin_dir_path( __FILE__ ) . 'build/index.asset.php';
	$script_url = plugins_url( 'build/index.js', __FILE__ );

	if ( ! file_exists( $asset_path ) ) {
		return;
	}

	$asset = require $asset_path;

	wp_enqueue_script(
		'hide-block-on-mobile-editor-script',
		$script_url,
		$asset['dependencies'],
		$asset['version'],
		true
	);

	// Set script translations for localization
	// To add translations: create languages/hide-block-on-mobile-de_DE.po/mo files
	wp_set_script_translations(
		'hide-block-on-mobile-editor-script',
		'hide-block-on-mobile',
		plugin_dir_path( __FILE__ ) . 'languages'
	);
}
add_action( 'enqueue_block_editor_assets', 'hbom_enqueue_editor_script' );
